# 測試配置
test_paths:
  unit_tests:
    - tests/CBO/ui/test_ui_admin改密碼後user重置密碼_cbo.py

  ui_tests:
    - tests/CBO_KBB/ui/test_ui_密碼修改失敗_kbb.py
    - tests/CBO_KBB/ui/test_ui_登入登出_kbb.py
    - tests/CBO_KBB/ui/test_ui_密碼登入錯誤_kbb.py
    - tests/CBO/ui/test_ui_密碼修改失敗_cbo.py
    - tests/CBO/ui/test_ui_登入登出_cbo.py
    - tests/CBO/ui/test_ui_密碼登入錯誤_cbo.py
    - tests/CBO/ui/test_ui_admin改密碼後user重置密碼_cbo.py
  
  api_tests:
    - tests/CBO_KBB/api/test_api_登入登出_kbb.py
    - tests/CBO_KBB/api/test_api_修改密碼失敗_kbb.py
    - tests/CBO/api/test_api_登入登出_cbo.py
    - tests/CBO/api/test_api_修改密碼失敗_cbo.py
  
  kbb_tests:
    - tests/CBO_KBB/api/test_api_登入登出_kbb.py
    - tests/CBO_KBB/api/test_api_修改密碼失敗_kbb.py
    - tests/CBO_KBB/ui/test_ui_密碼修改失敗_kbb.py
    - tests/CBO_KBB/ui/test_ui_登入登出_kbb.py
    - tests/CBO_KBB/ui/test_ui_密碼登入錯誤_kbb.py

  cbo_tests:
    - tests/CBO/api/test_api_登入登出_cbo.py
    - tests/CBO/api/test_api_修改密碼失敗_cbo.py
    - tests/CBO/ui/test_ui_密碼修改失敗_cbo.py
    - tests/CBO/ui/test_ui_登入登出_cbo.py
    - tests/CBO/ui/test_ui_密碼登入錯誤_cbo.py
    - tests/CBO/ui/test_ui_admin改密碼後user重置密碼_cbo.py

# 執行模式
mode: all, unit, ui, api, kbb, cbo # all, ui, api, smoke, custom
